### ISSUE TITLE
milestone

### ISSUE THREAD

**Issue by petermeissner** [petermeissner/diffrprojects#6]
- [x] coding alignments
- [x] testing 
- [x] inherit codings
- [x] testing
- ~~[ ] aggregation of results~~
- ~~[ ] testing~~
- [x] save and load
- [x] testing
- [x] import and export
- [x] testing
- [x] visualization of codings
- [x] testing
